
require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'

target 'App' do
  capacitor_pods
  # Add your other dependencies here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
